### ISSUE TITLE
Would it be okay to use your script as a template? 

### ISSUE THREAD

**Issue by CuriousTommy** [nonameentername/docker-devkitpro#3]
I just realize, while I was modifying my fork, that you do not have a license on your repo.

Would you be okay with me modifying your script and using it as a template? If you are not okay, I can delete the fork I made.

**Comment by nonameentername** [comment]
Yes, that's fine.  You can also submit pull request if you want.  I updated master with your changes.  I didn't know that there was a perl script that installed everything.

**Comment by CuriousTommy** [comment]
Awesome! If I have time and interest, I'll work more on it and submit a pull request.
